apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2016-02-17T07:57:48Z
  labels:
    name: etcd-storage
  name: etcd-storage
  namespace: openshift-origin
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  resources:
    limits:
      storage: 2Gi
    requests:
      storage: 2000Mi
status: {}
