apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-storage
  namespace: openshift-origin
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Recycle Delete Retain
  hostPath:
    path: /data/src/github.com/openshift/origin/openshift.local.etcd
