apiVersion: v1
kind: Pod
metadata: 
  name: etcd0
spec: 
  # hostNetwork: true
  containers: 
  - name: "etcd0"
    image: "quay.io/coreos/etcd"
    args: 
    - "--name=etcd0"
    - "--advertise-client-urls=http://10.0.0.1:2379"
    - "--listen-client-urls=http://0.0.0.0:2379"
    - "--listen-peer-urls=http://0.0.0.0:2380"
    - "--data-dir=/var/lib/etcd/data"
    - "--wal-dir=/var/lib/etcd/wal"
    - "--election-timeout=1000"
    - "--heartbeat-interval=100"
    - "--snapshot-count=10000"
    - "--max-snapshots=5"
    - "--max-wals=5"
    - "--initial-advertise-peer-urls=http://10.0.0.1:2380"
    - "--initial-cluster=etcd0=http://10.0.0.1:2380"
    - "--initial-cluster-state=new"
    - "--initial-cluster-token=etcd-cluster-1"
        ports:
          - name: client
            containerPort: 2379
            protocol: "TCP"
          - name: peer
            containerPort: 2380
            protocol: "TCP"
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
        volumeMounts:
          - name: "etcd-data"
            mountPath: /var/lib/etcd/data
          - name: "etcd-wal"
            mountPath: /var/lib/etcd/wal
    volumes:
      - name: "etcd-wal"
        awsElasticBlockStore:
          volumeID: vol-1234wal0
          fsType: ext4
      - name: "etcd-data"
        awsElasticBlockStore:
          volumeID: vol-1234data0
          fsType: ext4
