apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/hyperkube-amd64:v1.4.0-ci # v1.4.0-alpha.1 # v1.3.0-alpha.2 # v1.2.4
    imagePullPolicy: Never # Always IfNotPresent Never
    command:
    - /hyperkube
    - scheduler
    - --master=http://127.0.0.1:8080
    # - --address=172.17.4.50
    - --v=2
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1

